// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file orders.proto (package temporal.protobufes.fixture, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file orders.proto.
 */
export const file_orders = /*@__PURE__*/
  fileDesc("CgxvcmRlcnMucHJvdG8SG3RlbXBvcmFsLnByb3RvYnVmZXMuZml4dHVyZSJFChFTdGFydE9yZGVyUmVxdWVzdBIQCghvcmRlcl9pZBgBIAEoCRIQCghxdWFudGl0eRgCIAEoBRIMCgR0YWdzGAMgAygJIjYKEFN0YXJ0T3JkZXJSZXN1bHQSEAoIb3JkZXJfaWQYASABKAkSEAoIYWNjZXB0ZWQYAiABKAhiBnByb3RvMw");

/**
 * Describes the message temporal.protobufes.fixture.StartOrderRequest.
 * Use `create(StartOrderRequestSchema)` to create a new message.
 */
export const StartOrderRequestSchema = /*@__PURE__*/
  messageDesc(file_orders, 0);

/**
 * Describes the message temporal.protobufes.fixture.StartOrderResult.
 * Use `create(StartOrderResultSchema)` to create a new message.
 */
export const StartOrderResultSchema = /*@__PURE__*/
  messageDesc(file_orders, 1);

