// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file orders.proto (package temporal.protobufes.fixture, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orders.proto.
 */
export declare const file_orders: GenFile;

/**
 * @generated from message temporal.protobufes.fixture.StartOrderRequest
 */
export declare type StartOrderRequest = Message<"temporal.protobufes.fixture.StartOrderRequest"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: int32 quantity = 2;
   */
  quantity: number;

  /**
   * @generated from field: repeated string tags = 3;
   */
  tags: string[];
};

/**
 * Describes the message temporal.protobufes.fixture.StartOrderRequest.
 * Use `create(StartOrderRequestSchema)` to create a new message.
 */
export declare const StartOrderRequestSchema: GenMessage<StartOrderRequest>;

/**
 * @generated from message temporal.protobufes.fixture.StartOrderResult
 */
export declare type StartOrderResult = Message<"temporal.protobufes.fixture.StartOrderResult"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: bool accepted = 2;
   */
  accepted: boolean;
};

/**
 * Describes the message temporal.protobufes.fixture.StartOrderResult.
 * Use `create(StartOrderResultSchema)` to create a new message.
 */
export declare const StartOrderResultSchema: GenMessage<StartOrderResult>;

